openapi: 3.0.3
info:
  title: AAL2 Audit Log API
  description: |
    API for querying and exporting AAL2 authentication audit logs.
    All endpoints require 'Manage portal' permission.
  version: 1.0.0
  contact:
    name: c2.pas.aal2

servers:
  - url: /++api++/c2.pas.aal2/audit
    description: Audit log API base path

paths:
  /events:
    get:
      summary: Query audit events
      description: Retrieve audit log events with optional filtering
      operationId: queryAuditEvents
      parameters:
        - name: user_id
          in: query
          description: Filter by user ID
          required: false
          schema:
            type: string
          example: admin
        - name: action_type
          in: query
          description: Filter by action type
          required: false
          schema:
            type: string
            enum: [registration_start, registration_success, registration_failure,
                   authentication_start, authentication_success, authentication_failure,
                   credential_deleted, credential_updated,
                   aal2_timestamp_set, aal2_access_granted, aal2_access_denied,
                   aal2_policy_set, aal2_role_assigned, aal2_role_revoked]
          example: authentication_success
        - name: outcome
          in: query
          description: Filter by outcome
          required: false
          schema:
            type: string
            enum: [success, failure]
          example: success
        - name: start_date
          in: query
          description: Filter events after this date (ISO 8601 UTC)
          required: false
          schema:
            type: string
            format: date-time
          example: "2025-01-01T00:00:00Z"
        - name: end_date
          in: query
          description: Filter events before this date (ISO 8601 UTC)
          required: false
          schema:
            type: string
            format: date-time
          example: "2025-12-31T23:59:59Z"
        - name: limit
          in: query
          description: Maximum number of results (default 100, max 1000)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 100
          example: 50
        - name: offset
          in: query
          description: Number of results to skip for pagination
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
          example: 0
      responses:
        '200':
          description: Successful query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditEventListResponse'
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized (not logged in)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden (insufficient permissions)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /events/export:
    post:
      summary: Export audit events
      description: Export audit log events in CSV or JSON format
      operationId: exportAuditEvents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                format:
                  type: string
                  enum: [csv, json]
                  default: csv
                  description: Export format
                filters:
                  type: object
                  description: Same filters as GET /events
                  properties:
                    user_id:
                      type: string
                    action_type:
                      type: string
                    outcome:
                      type: string
                    start_date:
                      type: string
                      format: date-time
                    end_date:
                      type: string
                      format: date-time
              example:
                format: csv
                filters:
                  action_type: authentication_success
                  start_date: "2025-01-01T00:00:00Z"
                  end_date: "2025-12-31T23:59:59Z"
      responses:
        '200':
          description: Export file ready
          content:
            text/csv:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuditEvent'
        '400':
          description: Invalid export request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /events/{event_id}:
    get:
      summary: Get single audit event
      description: Retrieve details of a specific audit event by ID
      operationId: getAuditEvent
      parameters:
        - name: event_id
          in: path
          required: true
          description: UUID of the audit event
          schema:
            type: string
            format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: Event found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditEvent'
        '404':
          description: Event not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /stats:
    get:
      summary: Get audit log statistics
      description: Retrieve summary statistics about audit logs
      operationId: getAuditStats
      responses:
        '200':
          description: Statistics retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditStatsResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /cleanup:
    post:
      summary: Trigger audit log cleanup
      description: Manually trigger deletion of old audit logs based on retention policy
      operationId: cleanupAuditLogs
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                dry_run:
                  type: boolean
                  default: false
                  description: If true, report what would be deleted without actually deleting
              example:
                dry_run: true
      responses:
        '200':
          description: Cleanup completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  deleted_count:
                    type: integer
                    description: Number of events deleted
                  oldest_remaining:
                    type: string
                    format: date-time
                    description: Timestamp of oldest remaining event
                  dry_run:
                    type: boolean
                example:
                  deleted_count: 1234
                  oldest_remaining: "2025-01-15T00:00:00Z"
                  dry_run: false
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

components:
  schemas:
    AuditEvent:
      type: object
      required:
        - event_id
        - timestamp
        - user_id
        - action_type
        - outcome
        - ip_address
        - user_agent
        - metadata
      properties:
        event_id:
          type: string
          format: uuid
          description: Unique event identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        timestamp:
          type: string
          format: date-time
          description: UTC timestamp when event occurred
          example: "2025-01-15T10:30:45.123Z"
        user_id:
          type: string
          description: Plone user ID (or 'anonymous')
          example: "admin"
        action_type:
          type: string
          enum: [registration_start, registration_success, registration_failure,
                 authentication_start, authentication_success, authentication_failure,
                 credential_deleted, credential_updated,
                 aal2_timestamp_set, aal2_access_granted, aal2_access_denied,
                 aal2_policy_set, aal2_role_assigned, aal2_role_revoked]
          description: Type of security event
          example: "authentication_success"
        outcome:
          type: string
          enum: [success, failure]
          description: Whether the operation succeeded
          example: "success"
        ip_address:
          type: string
          description: Source IP address (IPv4 or IPv6)
          example: "192.168.1.100"
        user_agent:
          type: string
          description: Browser User-Agent header
          example: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0"
        metadata:
          type: object
          description: Action-specific additional data (varies by action_type)
          additionalProperties: true
          example:
            credential_id: "abc123xyz"
            sign_count: 42
            aal2_elevated: true

    AuditEventListResponse:
      type: object
      required:
        - items
        - total
        - limit
        - offset
      properties:
        items:
          type: array
          description: Array of audit events
          items:
            $ref: '#/components/schemas/AuditEvent'
        total:
          type: integer
          description: Total number of matching events (ignoring pagination)
          example: 1234
        limit:
          type: integer
          description: Maximum results per page
          example: 100
        offset:
          type: integer
          description: Number of results skipped
          example: 0
        filters_applied:
          type: object
          description: Echo of the filters used in the query
          additionalProperties: true
          example:
            user_id: "admin"
            action_type: "authentication_success"

    AuditStatsResponse:
      type: object
      properties:
        total_events:
          type: integer
          description: Total number of audit events stored
          example: 12345
        oldest_event:
          type: string
          format: date-time
          description: Timestamp of oldest event
          example: "2024-10-01T00:00:00Z"
        newest_event:
          type: string
          format: date-time
          description: Timestamp of newest event
          example: "2025-01-15T10:30:45Z"
        by_action_type:
          type: object
          description: Event counts by action type
          additionalProperties:
            type: integer
          example:
            authentication_success: 5678
            authentication_failure: 234
            registration_success: 123
        by_outcome:
          type: object
          description: Event counts by outcome
          properties:
            success:
              type: integer
            failure:
              type: integer
          example:
            success: 11111
            failure: 1234
        retention_policy:
          type: object
          description: Current retention policy settings
          properties:
            retention_days:
              type: integer
            last_cleanup:
              type: string
              format: date-time
            next_cleanup:
              type: string
              format: date-time
          example:
            retention_days: 90
            last_cleanup: "2025-01-14T00:00:00Z"
            next_cleanup: "2025-01-15T00:00:00Z"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "invalid_filter"
        message:
          type: string
          description: Human-readable error message
          example: "Invalid date format for start_date parameter"
        details:
          type: object
          description: Additional error details
          additionalProperties: true

  securitySchemes:
    ploneAuth:
      type: http
      scheme: basic
      description: Plone authentication (requires 'Manage portal' permission)

security:
  - ploneAuth: []
